# Generated by Django 6.0.3 on 2026-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_testanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testanswer',
            name='question_id',
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='correct_answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='is_correct',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='question_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user_answer',
            field=models.CharField(max_length=255),
        ),
    ]
