# Generated by Django 6.0.3 on 2026-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_testanswer_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='question_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
