# Generated by Django 6.0.3 on 2026-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_testanswer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testanswer',
            name='correct_answer_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='user_answer_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
