# Generated by Django 6.0.3 on 2026-03-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testanswer_correct_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswer',
            name='correct_answer',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='correct_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='question_text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='testanswer',
            name='user_answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
