# Generated by Django 6.0.3 on 2026-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_testresult_category_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
