# Generated by Django 6.0.3 on 2026-03-31 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_testresult_correct_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(default=0.0),
        ),
    ]
