# Generated by Django 6.0.3 on 2026-03-31 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_testresult_percent_alter_testresult_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(),
        ),
    ]
