# Generated by Django 6.0.3 on 2026-03-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_testresult_total_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.IntegerField(),
        ),
    ]
