# Generated by Django 6.0.3 on 2026-04-03 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_testresult_percent_alter_testresult_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='grade_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к оценке'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='grade_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выставления оценки'),
        ),
        migrations.CreateModel(
            name='LabWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('docx_file', models.FileField(upload_to='lab_works/', verbose_name='Файл .docx')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('difficulty', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_labs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(upload_to='lab_submissions/')),
                ('status', models.CharField(choices=[('submitted', 'Сдано'), ('under_review', 'На проверке'), ('graded', 'Проверено'), ('rejected', 'Отклонено')], default='submitted', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_labs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to=settings.AUTH_USER_MODEL)),
                ('lab_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='base.labwork')),
            ],
        ),
    ]
