# Generated by Django 6.0.3 on 2026-04-04 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_testresult_grade_testresult_grade_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='grade_comment',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='grade_date',
        ),
        migrations.AddField(
            model_name='testresult',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оценки'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_results', to=settings.AUTH_USER_MODEL, verbose_name='Оценку выставил'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий учителя'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(2, '2 - Неудовлетворительно'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично'), (None, 'Без оценки')], null=True, verbose_name='Оценка'),
        ),
    ]
