# Generated by Django 6.0.3 on 2026-04-05 05:17

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_testresult_grade_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labwork',
            name='docx_file',
            field=models.FileField(upload_to=base.models.lab_file_path, verbose_name='Файл.docx'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (0, 'Незачет')], null=True, verbose_name='Оценка'),
        ),
    ]
