# Generated by Django 6.0.3 on 2026-04-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_labwork_docx_file_alter_testresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='labwork',
            name='pptx_file',
            field=models.FileField(blank=True, null=True, upload_to='media/pptx_files/'),
        ),
    ]
