# Generated by Django 6.0.3 on 2026-04-06 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_testcategory_testquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestKindCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_count', models.IntegerField(default=5, help_text='0 - все вопросы категории', verbose_name='Количество вопросов')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.testcategory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestKindConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('start', 'Входное тестирование'), ('final', 'Итоговое тестирование')], max_length=10, unique=True, verbose_name='Код типа теста')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('template', models.CharField(max_length=100, verbose_name='Шаблон теста')),
                ('result_template', models.CharField(max_length=100, verbose_name='Шаблон результатов')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(related_name='test_kinds', through='base.TestKindCategory', to='base.testcategory', verbose_name='Категории теста')),
            ],
            options={
                'verbose_name': 'Конфигурация теста',
                'verbose_name_plural': 'Конфигурации тестов',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='testkindcategory',
            name='test_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.testkindconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='testkindcategory',
            unique_together={('test_kind', 'category')},
        ),
    ]
