# Generated by Django 6.0.3 on 2026-04-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_testkindcategory_testkindconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Импортирован из БД'),
        ),
    ]
