# Generated by Django 6.0.3 on 2026-04-07 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_testquestion_is_imported'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('start', 'Входное тестирование'), ('final', 'Итоговое тестирование'), ('teacher', 'Тест от учителя')], max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('assigned_to', models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'student'}, related_name='assigned_tests', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.testquestion')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teachertest')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('test', 'question')},
            },
        ),
        migrations.AddField(
            model_name='teachertest',
            name='questions',
            field=models.ManyToManyField(related_name='teacher_tests', through='base.TeacherTestQuestion', to='base.testquestion'),
        ),
    ]
