# Generated by Django 6.0.3 on 2026-04-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_testquestion_created_by_alter_testresult_test_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsubmission',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
