# Generated by Django 6.0.3 on 2026-04-10 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_labsubmission_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='teacher_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='base.teachertest', verbose_name='Тест учителя'),
        ),
    ]
