# Generated by Django 6.0.3 on 2026-05-01 05:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertest',
            name='auto_assign_new_students',
            field=models.BooleanField(default=True, verbose_name='Автоматически назначать новым ученикам'),
        ),
        migrations.AlterField(
            model_name='teachertest',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to={'profile__role': 'student'}, related_name='assigned_tests', to=settings.AUTH_USER_MODEL, verbose_name='Конкретные ученики (оставьте пустым для всех)'),
        ),
    ]
