# Generated by Django 6.0.3 on 2026-05-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_teachertest_auto_assign_new_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_lab', 'Новая лабораторная работа'), ('new_test', 'Новый тест'), ('lab_submitted', 'Сдана лабораторная работа'), ('test_completed', 'Пройден тест'), ('lab_graded', 'Проверена лабораторная работа'), ('test_graded', 'Проверен тест'), ('lab_comment', 'Добавлен комментарий к лабораторной'), ('new_student', 'Новый ученик')], max_length=20),
        ),
    ]
