# Generated by Django 6.0.3 on 2026-05-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_teacherstudentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentmessage',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/'),
        ),
        migrations.AddField(
            model_name='teacherstudentmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teacherstudentmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текст'), ('voice', 'Голосовое сообщение'), ('file', 'Файл')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='teacherstudentmessage',
            name='reactions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='teacherstudentmessage',
            name='voice_duration',
            field=models.IntegerField(default=0, help_text='Длительность в секундах'),
        ),
        migrations.AddField(
            model_name='teacherstudentmessage',
            name='voice_message',
            field=models.FileField(blank=True, null=True, upload_to='voice_messages/'),
        ),
        migrations.AlterField(
            model_name='teacherstudentmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения'),
        ),
    ]
